name: Android CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon buildDebug assembleDebug
      - name: Upload debug apk
        uses: actions/upload-artifact@v3
        with:
          name: boom-switch-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
